import Link from "next/link";
import { ArrowRight, BookOpenCheck, Bot, CheckCircle2, Gamepad2, Lightbulb, Rocket, Sparkles, WandSparkles } from "lucide-react";
import { SectionHeading } from "@/components/section-heading";
import { ContentCard } from "@/components/content-card";
import { getContentList } from "@/lib/content";
export default function HomePage() { const lessons = getContentList("lessons").slice(0, 3); const games = getContentList("games").slice(0, 4); return <>
  <section className="hero"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> Google AI Studio cho giáo viên</span><h1>Biến bài học thành <span>trải nghiệm</span> học tập.</h1><p>Không cần biết lập trình. Đi từ giáo án đến game tương tác bằng một quy trình rõ ràng, prompt tốt và sự hỗ trợ đúng lúc.</p><div className="hero-actions"><Link className="button" href="/builder"><WandSparkles size={19}/> Tạo Prompt đầu tiên</Link><Link className="button secondary" href="/learn"><BookOpenCheck size={19}/> Bắt đầu khóa học</Link></div><div className="trust-row"><span><CheckCircle2/> Miễn phí</span><span><CheckCircle2/> Không đăng nhập</span><span><CheckCircle2/> Dành cho người mới</span></div></div>
  <div className="hero-lab" aria-label="Minh họa quy trình tập huấn"><div className="lab-top"><span className="dot red"/><span className="dot amber"/><span className="dot green"/><b>Phòng thí nghiệm của Giáo viên</b></div><div className="lab-card lesson"><span><BookOpenCheck/></span><div><small>Bài học đầu vào</small><b>Vòng tuần hoàn của nước</b><p>Khoa học · Lớp 4</p></div></div><div className="flow-line"><span/><Bot/><span/></div><div className="lab-card output"><div className="game-mini"><span>☁️</span><b>Hành trình giọt nước</b><div className="mini-options"><i/><i/><i/></div></div><div><small>Sản phẩm đã sẵn sàng</small><b>Quiz tương tác</b><p>10 câu · 8 phút</p></div></div><div className="floating-note"><Lightbulb/> Tạo trong 5 phút</div></div></div></section>
  <section className="section process-section"><div className="container"><SectionHeading centered eyebrow="Một quy trình, một sản phẩm" title="Từ ý tưởng đến lớp học trong 4 bước">Chương trình tập huấn dẫn đường để bạn tập trung vào chuyên môn sư phạm, thay vì loay hoay với công nghệ.</SectionHeading><div className="process-grid">{[[BookOpenCheck,"01","Đưa bài học vào","Dán nội dung giáo án hoặc mô tả điều học sinh cần đạt."],[Bot,"02","AI sắp xếp ý tưởng","Chọn dạng game; hệ thống giúp cấu trúc yêu cầu rõ ràng."],[WandSparkles,"03","Nhận Prompt tối ưu","Sao chép prompt hoàn chỉnh và mở Google AI Studio."],[Rocket,"04","Chỉnh sửa & chia sẻ","Thử sản phẩm, yêu cầu AI điều chỉnh rồi triển khai."]].map(([Icon,n,t,d]) => { const I = Icon as typeof Bot; return <article className="process-card" key={String(n)}><span className="step-number">{String(n)}</span><div className="icon-box"><I/></div><h3>{String(t)}</h3><p>{String(d)}</p></article>})}</div></div></section>
  <section className="section soft-section"><div className="container"><SectionHeading eyebrow="Học bằng cách làm" title="Khóa học ngắn, kết quả thật">Mỗi bài chỉ 8–15 phút, có thực hành và prompt mẫu để dùng ngay.</SectionHeading><div className="card-grid three">{lessons.map((x,i) => <ContentCard item={x} base="/learn" index={i} key={x.slug}/>)}</div><div className="section-action"><Link className="text-link big" href="/learn">Xem lộ trình đầy đủ <ArrowRight/></Link></div></div></section>
  <section className="section"><div className="container split-heading"><SectionHeading eyebrow="Chọn đúng hoạt động" title="10 mẫu game cho mọi bài học">Từ ôn tập nhanh đến khám phá theo nhóm, luôn có một cấu trúc phù hợp mục tiêu.</SectionHeading><Link className="button secondary" href="/games">Mở thư viện <ArrowRight/></Link></div><div className="container game-strip">{games.map((game,i) => <Link href={`/games/${game.slug}`} className={`game-tile tone-${game.color}`} key={game.slug}><span><Gamepad2/></span><small>0{i+1}</small><h3>{game.title}</h3><p>{game.description}</p><ArrowRight/></Link>)}</div></section>
  <section className="section final-cta"><div className="container cta-box"><div><span className="eyebrow"><Sparkles size={15}/> Sẵn sàng cho bài học tiếp theo?</span><h2>Một prompt tốt có thể mở ra cả một lớp học sôi động.</h2><p>Hãy bắt đầu với bài bạn sắp dạy. Hệ thống sẽ giúp bạn làm phần còn lại.</p></div><Link className="button light" href="/builder">Tạo sản phẩm ngay <ArrowRight/></Link></div></section>
  </> }


