"use client";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Bot, Check, ChevronLeft, ChevronRight, Clipboard, Download, ExternalLink, FileText, Gamepad2, LoaderCircle, RotateCcw, Settings2, Sparkles } from "lucide-react";
import { useAIConnection } from "@/components/ai-connection-provider";
import { gameTypes, siteConfig, subjects } from "@/lib/constants";
import { buildPrompt } from "@/lib/prompt-engine/templates";
import { defaultPromptInput, type PromptInput } from "@/lib/prompt-engine/types";
import { useLocalStorage } from "@/hooks/use-local-storage";
const steps=[{n:1,t:"Bài học",i:FileText},{n:2,t:"Trò chơi",i:Gamepad2},{n:3,t:"Tinh chỉnh",i:Settings2},{n:4,t:"Prompt",i:Sparkles}];
const upgrades=[{v:"responsive",l:"Responsive"},{v:"score",l:"Lưu điểm"},{v:"animation",l:"Animation"},{v:"sound",l:"Âm thanh"},{v:"dark",l:"Dark mode"},{v:"leaderboard",l:"Leaderboard"},{v:"pwa",l:"PWA"},{v:"offline",l:"Offline"},{v:"accessibility",l:"Accessibility"}];
export function PromptBuilder(){ const search=useSearchParams(); const { runTask }=useAIConnection(); const [data,setData]=useLocalStorage<PromptInput>("teachermate-prompt-draft",defaultPromptInput); const [step,setStep]=useState(1); const [copied,setCopied]=useState(false); const [aiLoading,setAILoading]=useState(false); const [aiStatus,setAIStatus]=useState(""); useEffect(()=>{const game=search.get("game"); if(game && gameTypes.some(x=>x.value===game)) setData(x=>({...x,gameType:game}));},[search,setData]); const prompt=useMemo(()=>buildPrompt(data),[data]); function patch<K extends keyof PromptInput>(key:K,value:PromptInput[K]){setData(x=>({...x,[key]:value}))} function toggle(v:string){patch("upgrades",data.upgrades.includes(v)?data.upgrades.filter(x=>x!==v):[...data.upgrades,v])} async function improveObjectives(){setAILoading(true);setAIStatus("");try{const result=await runTask({task:"improve-learning-objectives",requirement:{capabilities:["text"],preferStable:true,preferFreeOrLowCost:true,allowPreview:false},input:{subject:data.subject,grade:data.grade,lessonName:data.lessonName,currentObjectives:data.objectives,lessonContent:data.content.slice(0,6000)}});patch("objectives",result.output);setAIStatus(`Đã dùng ${result.model} ở chế độ ${result.mode==="auto"?"Tự động":"Thủ công"}.`)}catch(error){setAIStatus(error instanceof Error?error.message:"Không thể dùng trợ lý AI.")}finally{setAILoading(false)}} async function copy(){await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1800)} function download(){const blob=new Blob([prompt],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`prompt-${data.lessonName||"google-ai-studio"}.txt`;a.click();URL.revokeObjectURL(url)} return <section className="builder-section"><div className="container builder-shell"><aside className="builder-steps">{steps.map(s=>{const Icon=s.i;return <button key={s.n} onClick={()=>setStep(s.n)} className={`${step===s.n?"active":""} ${step>s.n?"done":""}`}><span>{step>s.n?<Check/>:<Icon/>}</span><small>Bước {s.n}</small><b>{s.t}</b></button>})}<div className="save-note"><Check/><span><b>Tự động lưu</b>Dữ liệu chỉ nằm trên thiết bị này.</span></div></aside><div className="builder-main">
{step===1&&<div className="form-step"><div className="form-heading"><small>Bước 1 / 4</small><h2>Kể cho chúng tôi về bài học</h2><p>Không cần viết hoàn hảo. Hãy nhập đúng những gì bạn đang có.</p></div><div className="field-grid"><label>Môn học<select value={data.subject} onChange={e=>patch("subject",e.target.value)}>{subjects.map(x=><option key={x}>{x}</option>)}</select></label><label>Khối lớp<select value={data.grade} onChange={e=>patch("grade",e.target.value)}>{Array.from({length:12},(_,i)=>`Lớp ${i+1}`).map(x=><option key={x}>{x}</option>)}</select></label></div><label>Tên bài học<input placeholder="Ví dụ: Vòng tuần hoàn của nước" value={data.lessonName} onChange={e=>patch("lessonName",e.target.value)}/></label><label><span className="ai-field-heading"><span>Mục tiêu học tập</span><button type="button" onClick={improveObjectives} disabled={aiLoading}>{aiLoading?<LoaderCircle className="spin"/>:<Bot/>} AI gợi ý mục tiêu</button></span><textarea rows={3} placeholder="Sau bài học, học sinh có thể..." value={data.objectives} onChange={e=>patch("objectives",e.target.value)}/></label>{aiStatus&&<p className="ai-task-status">{aiStatus}</p>}<label>Nội dung bài học<textarea rows={7} placeholder="Dán giáo án, nội dung sách giáo khoa hoặc tóm tắt kiến thức..." value={data.content} onChange={e=>patch("content",e.target.value)}/><span className="field-help">Không nhập thông tin cá nhân của học sinh.</span></label></div>}
{step===2&&<div className="form-step"><div className="form-heading"><small>Bước 2 / 4</small><h2>Chọn cách học sinh sẽ chơi</h2><p>Hãy chọn theo mục tiêu của bài, không chỉ theo hình thức đẹp mắt.</p></div><div className="game-choice-grid">{gameTypes.map((x,i)=><button key={x.value} className={data.gameType===x.value?"selected":""} onClick={()=>patch("gameType",x.value)}><span>{["?","#","↔","◫","★","↕","⌂","↗","▤","◉"][i]}</span><b>{x.label}</b><small>{["Kiểm tra nhanh","Ôn từ khóa","Nối khái niệm","Ghi nhớ hình ảnh","Thi đua cả lớp","Phân loại kiến thức","Giải đố theo nhóm","Sắp xếp sự kiện","Học từ vựng","Chọn ngẫu nhiên"][i]}</small>{data.gameType===x.value&&<Check/>}</button>)}</div></div>}
{step===3&&<div className="form-step"><div className="form-heading"><small>Bước 3 / 4</small><h2>Tinh chỉnh trải nghiệm</h2><p>Một vài chi tiết đúng sẽ giúp sản phẩm vừa sức và hợp lớp học hơn.</p></div><div className="field-grid"><label>Số câu hỏi<input type="number" min={3} max={30} value={data.questionCount} onChange={e=>patch("questionCount",Number(e.target.value))}/></label><label>Thời lượng (phút)<input type="number" min={3} max={45} value={data.duration} onChange={e=>patch("duration",Number(e.target.value))}/></label></div><label>Từ khóa bắt buộc<input placeholder="bay hơi, ngưng tụ, mưa..." value={data.keywords} onChange={e=>patch("keywords",e.target.value)}/></label><label>Phong cách giao diện<select value={data.visualStyle} onChange={e=>patch("visualStyle",e.target.value)}><option>Tươi sáng, thân thiện với học sinh</option><option>Tối giản, tập trung vào nội dung</option><option>Vũ trụ và khám phá</option><option>Thiên nhiên và môi trường</option><option>Pixel art vui nhộn</option><option>Trang trọng, phù hợp THPT</option></select></label><fieldset><legend>Tính năng thêm</legend><div className="chip-grid">{upgrades.map(x=><button type="button" className={data.upgrades.includes(x.v)?"selected":""} key={x.v} onClick={()=>toggle(x.v)}>{data.upgrades.includes(x.v)&&<Check/>}{x.l}</button>)}</div></fieldset></div>}
{step===4&&<div className="form-step result-step"><div className="form-heading"><small>Bước 4 / 4</small><h2>Prompt của bạn đã sẵn sàng</h2><p>Đọc nhanh nội dung, sao chép rồi gửi vào Google AI Studio Build mode.</p></div><div className="prompt-toolbar"><span><i/> Prompt hoàn chỉnh · {prompt.length.toLocaleString("vi-VN")} ký tự</span><button onClick={()=>setData(defaultPromptInput)}><RotateCcw/> Làm mới</button></div><pre className="prompt-preview">{prompt}</pre><div className="result-actions"><button className="button" onClick={copy}>{copied?<><Check/>Đã sao chép</>:<><Clipboard/>Sao chép Prompt</>}</button><button className="button secondary" onClick={download}><Download/>Tải .txt</button><a className="button studio" href={siteConfig.aiStudioUrl} target="_blank" rel="noreferrer">Mở AI Studio <ExternalLink/></a></div><div className="next-instruction"><b>Tiếp theo làm gì?</b><ol><li>Mở Google AI Studio và chọn Build.</li><li>Dán prompt vào ô mô tả ứng dụng.</li><li>Chờ tạo xong, thử game và yêu cầu chỉnh sửa từng phần.</li></ol></div></div>}
<div className="form-nav"><button className="button secondary" disabled={step===1} onClick={()=>setStep(x=>x-1)}><ChevronLeft/> Quay lại</button>{step<4&&<button className="button" onClick={()=>setStep(x=>x+1)}>Tiếp tục <ChevronRight/></button>}</div></div></div></section> }

